workflows:
  ios-build:
    name: Drive KL Rental iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: "com.drivekl.rental"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: latest  # Uses latest LTS Node.js (20+)
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - ~/.npm
        - ~/Library/Caches/CocoaPods
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Verify Node.js version
        script: |
          echo "Node.js version:"
          node --version
          echo "NPM version:"
          npm --version
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
      - name: Verify Capacitor CLI
        script: |
          npx cap --version
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Setup iOS dependencies
        script: |
          cd ios/App && pod install
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Set up provisioning profiles (Development)
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_DEVELOPMENT \
            --create
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true