workflows:
  ios-manual-signing:
    name: Drive KL Rental iOS (Manual Signing)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - ios_manual_signing  # Create this group in Codemagic with certificate files
      vars:
        BUNDLE_ID: "com.drivekl.rental"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: latest
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - ~/.npm
        - ~/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Verify environment
        script: |
          echo "Node.js: $(node --version)"
          echo "Xcode: $(xcodebuild -version)"
          echo "CocoaPods: $(pod --version)"
      - name: Install Node dependencies
        script: |
          npm ci
      - name: Build web application
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install iOS dependencies
        script: |
          cd ios/App && pod install
      - name: Set up keychain (Manual)
        script: |
          keychain initialize
      - name: Import certificates (Manual)
        script: |
          # Import manually uploaded certificate from environment group
          keychain add-certificates
      - name: Update project settings
        script: |
          cd ios/App
          # Set development team and bundle identifier
          sed -i '' "s/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = $APPLE_DEVELOPER_TEAM_ID;/" App.xcodeproj/project.pbxproj
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/" App.xcodeproj/project.pbxproj
      - name: Build signed iOS app
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -allowProvisioningUpdates \
            archive
      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR \
            -exportOptionsPlist ../../export-options-manual.plist
    artifacts:
      - "*.ipa"
      - "App.xcarchive"
      - ios/App/build/Build/Logs/
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true