workflows:
  ios-testflight:
    name: Drive KL Rental iOS - TestFlight
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic_app_store_connect
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.drivekl.rental"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_APPLE_ID: "m.aqibnadeem@live.com"
      node: latest
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - ~/.npm
        - ~/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Verify environment
        script: |
          echo "Node.js: $(node --version)"
          echo "Bundle ID: $BUNDLE_ID"
          echo "Apple ID: $APP_STORE_APPLE_ID"
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web application
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install iOS dependencies
        script: |
          cd ios/App && pod install
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_STORE \
            --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_CONNECT_APP_ID") + 1))
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - m.aqibnadeem@live.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false